### ISSUE TITLE
close menu

### ISSUE THREAD

**Issue by GauravCreed** [devsideal/SquareMenu#5]
@devsideal 

can we close menu manually after perform click operation

**Comment by devendroid** [comment]
this feature is not in current version but good idea, i will add in next version.

**Comment by devendroid** [comment]
Done in [new release](https://github.com/devendroid/SquareMenu)

use  `app:autoClose="true/false"` in xml
or  `mSquareMenu.setAutoClose(true/false);`  in java

**Comment by GauravCreed** [comment]
@devendroid 

Thanks. Keep it up.... You have done a **Great Work**
